### ISSUE TITLE
When map closed, getting this stopLocate error

### ISSUE THREAD

**Issue by dineshkumar02** [runette/ngx-leaflet-locate#4] opened 2022-06-30 16:56 UTC
Thank you for this package as it's working nice.

I am currently using this in one of my application, and whenever I close the model(which has map inside)
I am getting this error message.

Would like to request to share your suggestions on this.

```
ERROR TypeError: Cannot read properties of null (reading 'stopLocate')
    at NewClass._deactivate (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.mjs:33:36)
    at NewClass.stop (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.mjs:27:296)
    at NgxLeafletLocateComponent.ngOnDestroy (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.mjs:62:69)
    at executeOnDestroys (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:7368:1)
```

**Comment by runette** [comment] 2022-07-01 07:45
Interesting

It looks like it is coming from this line https://github.com/runette/ngx-leaflet-locate/blob/8df7481e816b3fafc18d252176e35c3a7c7d8686/src/lib/ngx-leaflet-locate.component.ts#L23

I have looked at the underlying leaflet.locatecontrol package and it comes down to this line 

https://github.com/domoritz/leaflet-locatecontrol/blob/5fd9018a6a74aa31cf871f318bb8927b72b47568/src/L.Control.Locate.js#L520

All in all - it looks like this happens when the map is destroyed before the locate control.

I am guessing that you have code in your ngOnDestroy that is destroying the map and the timing is slightly different to the test app!

A quick fix would be to remove that code (or to explicitly destroy the control before destroying the map). I will create a PR to add a test to avoid this error and push that in the next version.

**Comment by runette** [comment] 2022-07-01 11:27
version 2.0.

**Comment by runette** [comment] 2022-07-01 14:17
That is a bit weird. It looks like a problem ith the underlying locate control package - in which case you are going to have raise an issue with https://github.com/domoritz/leaflet-locatecontrol.

But - if you send me the code from your component - I could try to see if I can reproduce the problem

**Comment by dineshkumar02** [comment] 2022-09-21 19:32
Hi @runette,

Sorry for the late reply, and here is the component code I am using.

```


<div id='map' class="map-container" leaflet [style]="mapStyle" leafletPing
  (leafletPingObserver)="setLeafletPingObserver($event)" leafletDraw [leafletOptions]="options"
  [leafletDrawOptions]="drawOptions" (leafletDrawCreated)="onDrawCreated($event)" (leafletMapReady)="onMapReady($event)"
  (leafletDrawDeleted)="mapCleared($event)" (leafletDrawMarkerContext)="onMarker($event)" leafletPing
  (leafletPingObserver)="setLeafletPingObserver($event)">
  <div [leafletLayer]="drawnItems"></div>
</div>

<leaflet-fullscreen-control [map]="map" [options]="fullscreenOptions"></leaflet-fullscreen-control>

<leaflet-locate-control [map]="map" [options]="locateOptions" (location$)="onNewLocation($event)">
</leaflet-locate-control>

```


```
  onNewLocation(e: LocationEvent) {
    console.log(e.latlng);
  }
```


I am still getting the same error 
```

ERROR TypeError: Cannot read properties of null (reading 'stopLocate')
    at NewClass._deactivate (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.js:44:6423)
    at NewClass.stop (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.js:44:5444)
    at NgxLeafletLocateComponent.ngOnDestroy (c:\Users\dines\workspace\ecom-admin\node_modules\@runette\ngx-leaflet-locate\fesm2015\runette-ngx-leaflet-locate.js:64:26)
    at executeOnDestroys (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:7368:1)
    at cleanUpView (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:7271:1)
    at destroyViewTree (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:7104:1)
    at destroyLView (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:7249:1)
    at RootViewRef.destroy (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:21290:1)
    at ComponentRef.destroy (c:\Users\dines\workspace\ecom-admin\node_modules\@angular\core\fesm2015\core.mjs:21696:1)
    at DomPortalOutlet._disposeFn (http://localhost:4200/vendor.js:160004:22) {stack: 'TypeError: Cannot read properties of null (re…n (http://localhost:4200/vendor.js:160004:22)', message: 'Cannot read properties of null (reading 'stopLocate')'}
```

**Comment by neldrak** [comment] 2022-09-28 13:11
Having the exact same issue.

**Comment by neldrak** [comment] 2022-09-28 13:39
The locate me is registering twice on the "unload" event and the 2nd time it is called, the this._map is null:
![image](https://user-images.githubusercontent.com/6306734/192793665-72f4cdf7-f29c-45f2-b171-3e4716365e0e.png)

**Comment by neldrak** [comment] 2022-09-28 14:03
So we did a bunch of testing and looks like the ngx-leaftlet ngOnDestroy runs first, all fine.
Then the ngOnDestroy of the NgxLeafletLocateComponent runs and your code calls the this.control.stop() which works fine.
But then ngx-leaflet removes the map, which triggers the unload event from leaflet, which the locate control is registered to.
This then tries to run the stopLocate which fails, cause the map instance is already gone, cause the ngx-leaftlet component, which held the reference, is long gone.

We fixed it by unregistering the unload event from the locate control, after we ran the stop in the ngOnDestroy.
No need for it to run again, cause we dealt with it, right?

```
        if (this.control && this.map) {
            this.control.stop();
            this._map.off("unload", this.control._unload, this.control)
        }

```

Do you want a PR or is this enough? (researching it already cost me 2h :D)

**Comment by neldrak** [comment] 2022-09-28 14:04
thanks for your great work btw!

**Comment by silenum** [comment] 2022-11-15 19:44
Any news on this issue? What about the pending pull request? Is it going to be merged?

**Comment by runette** [comment] 2022-11-17 00:19
Sorry  - had a lot going on. Will try to get to this this week

**Comment by silenum** [comment] 2022-11-22 17:05
Hi, do you still have a lot going on? I am looking forward to using the merged feature. :)

**Comment by runette** [comment] 2022-11-22 17:27
I tried it - and got some errors when building the package. see the PR

**Comment by silenum** [comment] 2022-11-22 18:02
Thanks for letting me know. @neldrak do you have an idea of where the problem originates?

**Comment by runette** [comment] 2022-11-25 16:55
@silenum @neldrak I had a couple of hours on a train so I debugged the previous PR, tested it and released it as version 2.0.5.

See if that fixes your problems

**Comment by silenum** [comment] 2022-11-26 21:51
@runette thanks for the update. I integrated the latest version into the project. Unfortunately, the problem persists, see the screenshot.

![image](https://user-images.githubusercontent.com/43389781/204110180-fbd9c58d-be17-4b73-98e3-65346eb93823.png)

**Comment by runette** [comment] 2022-11-26 22:07
I don't think that there is anything else that can be done in this wrapper - the problem is in the underlying leaflet.locatecontrol library and really needs to be solved there.

If you think otherwise - I would be more than happy to receive and process another PR.

I cannot even reproduce the problem - so there is a limit to what I can do.

**Comment by goncalocaraujo** [comment] 2022-11-30 10:08
I don't know if this information is relevant or not but I noticed that this problem only happens if we use "rouerLink". If we use "href" it doesn't happen.

**Comment by runette** [comment] 2022-11-30 11:14
What would help would be if you could create a minimum project to replicate the problem. That would definitely help with trying to create a permanent fix.

But - what is really happening is that Angular - being event driven - is in certain circumstances calling destroy on the control after the map is destroyed. That is going to be very difficult to police. The underlying control has the bug that if the control is stopped after the map is destroyed - it crashes. We can keep patching at this level but the real fix is to patch the bug in the underlying control.

**Comment by runette** [comment] 2022-11-30 11:55
I submitted a PR to the parent with, hopefully, a fix.

It would be good if you test if this is a fix while we are waiting. Run the following command to use the PR version

```
npm install https://github.com/runette/leaflet-locatecontrol.git#fix-stopLocate
```

**Comment by Rlima2** [comment] 2022-11-30 17:06
@runette i use angular so i'm working with ngx-leaflet-locate, i have a exemple project with the problem for you https://github.com/Rlima2/bug-map-exemple

**Comment by runette** [comment] 2022-11-30 17:58
@Rlima2 thanks - I will give it a try

**Comment by runette** [comment] 2022-11-30 22:29
The update to the underlying control has been published

**Comment by runette** [comment] 2022-12-01 11:26
The latest version of leaflet.locatecontrol has fixed the problem (thanks to @domoritz for turning around and @Rlima2 for the test project).

Version  2.0.6 of this package implements that version and is no longer causing the problem in the test project.

I am closing this issue - please reopen if you still think you have problems

**Closed by runette** 2022-12-01 11:26 UTC

**Comment by silenum** [comment] 2022-12-04 14:17
Hi @runette 

I am happy to confirm that v2.0.6 does not throw the error in my project either. Thanks for your effort! :)
